@startuml
skinparam class {
  BackgroundColor<<data>> PaleGreen
  BackgroundColor<<proxy>> PaleRed
  ArrowColor #222222
  BorderColor #222222
}
skinparam linetype polyline
hide circles
hide stereotype
set separator ::

class "<b><size:17>TheFirstType</size></b>" as TheFirstType  {
-- Responsibilities --
  <b>[R]</b> A responsibility
  :::<b>[E]</b> An example for the responsibility
-- Examples --
  <b>[E]</b> An example for the Type
}
TheFirstType --> Package::ASecondType : A collaboration with\nPackage::ASecondType
TheFirstType --> ADataType : Creates ADataType
class "<b><size:17>Package::ASecondType</size></b>" as Package::ASecondType  {
-- Responsibilities --
  <b>[R]</b> consumes fuel
}
Package::ASecondType --> ADataType : Read ADataType
class "<b><size:17>Package::ASecondTypeBla</size></b>" as Package::ASecondTypeBla  {
-- Responsibilities --
  <b>[R]</b> it does other stuff
}
Package::ASecondTypeBla --> ADataType : Reads and writes\nADataType
Package::ASecondType <|-- Package::ASecondTypeBla
class "<b><size:17>ADataType [*]</size></b>" as ADataType <<data>> {
-- Responsibilities --
  <b>[R]</b> stores some stuff
  :::<b>[E]</b> such as bananas
}
circle SomethingFromSomewhere
@enduml
